syntax = "proto3";

package Fuel;

enum FuelType {
  UNKNOWN = 0;
  AI92 = 1;
  AI95 = 2;
  AI95F = 3;
  DT = 4;
  AI100 = 5;
}

service FuelReservation {
  rpc StartFueling (StartRequest) returns (StartResponse);
  rpc StopFueling  (StopRequest)  returns (StopResponse);
  rpc AddFuel      (AddFuelRequest) returns (AddFuelResponse);
}

message StartRequest {
  string pump_id              = 1;
  FuelType fuel_type            = 2;
  double preauthorized_litres = 3;
}

message StartResponse {
  bool   success         = 1;
  string session_id      = 2;
  double reserved_litres = 3;
  string error           = 4;
}

message StopRequest {
  string session_id    = 1;
  FuelType fuel_type   = 2;
  double actual_litres = 3;
}

message StopResponse {
  bool   success = 1;
  string error   = 2;
}

message AddFuelRequest {
  string fuel_type = 1;
  double litres    = 2;
}

message AddFuelResponse {
  bool   success    = 1;
  string tank_id    = 2;
  double new_volume = 3;
  string error      = 4;
}