syntax = "proto3";

package Fuel;

enum FuelType {
  UNKNOWN = 0;
  AI92 = 1;
  AI95 = 2;
  AI95F = 3;
  DT = 4;
  AI100 = 5;
}

service FuelReservation {
  rpc StartFuelling (StartFuellingRequest) returns (StartFuellingResponse);
  rpc CompleteFuelling  (CompleteFuellingRequest)  returns (CompleteFuellingResponse);
  rpc AddFuelFast      (AddFuelFastRequest) returns (AddFuelFastResponse);

  rpc StartDelivery   (StartDeliveryRequest)   returns (StartDeliveryResponse);
  rpc CompleteDelivery(CompleteDeliveryRequest) returns (CompleteDeliveryResponse);
}

message StartFuellingRequest {
  string pump_id              = 1; // empty string means auto-selection by server
  FuelType fuel_type            = 2;
  double preauthorized_litres = 3;
}

message StartFuellingResponse {
  bool   success         = 1;
  string session_id      = 2;
  double reserved_litres = 3;
  string error           = 4;
}

message CompleteFuellingRequest {
  string session_id    = 1;
  FuelType fuel_type   = 2;
  double actual_litres = 3;
}

message CompleteFuellingResponse {
  bool   success = 1;
  string error   = 2;
}

message AddFuelFastRequest {
  string fuel_type = 1;
  double litres    = 2;
}

message AddFuelFastResponse {
  bool   success    = 1;
  string tank_id    = 2;
  double new_volume = 3;
  string error      = 4;
}

message StartDeliveryRequest {
  repeated Compartment compartments = 1;
}

message StartDeliveryResponse {
  bool success = 1;
  string session_id = 2;
  string error = 3;
}

message CompleteDeliveryRequest {
  string session_id = 1;
}

message CompleteDeliveryResponse {
  bool success = 1;
  string error = 2;
}

message Compartment {
  FuelType fuel_type = 1;
  double litres = 2;
}