// <auto-generated />
using System;
using FuelStation.ReservationService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuelStation.ReservationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717120956_AddSessionEntities")]
    partial class AddSessionEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.DeliveryCompartmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DeliverySessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double>("Litres")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeliverySessionId");

                    b.ToTable("delivery_compartments", (string)null);
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.DeliverySessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("delivery_sessions", (string)null);
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.FuellingSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal?>("ActualVolume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("PumpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ReservedVolume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TankId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PumpId");

                    b.HasIndex("TankId");

                    b.ToTable("fuelling_sessions", (string)null);
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.NozzleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("PumpId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TankId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PumpId");

                    b.HasIndex("TankId");

                    b.ToTable("nozzles", (string)null);
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.PumpEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("pumps", (string)null);
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.TankEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CurrentVolume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("tanks", (string)null);
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.DeliveryCompartmentEntity", b =>
                {
                    b.HasOne("FuelStation.ReservationService.Persistence.Entities.DeliverySessionEntity", "DeliverySession")
                        .WithMany("Compartments")
                        .HasForeignKey("DeliverySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliverySession");
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.FuellingSessionEntity", b =>
                {
                    b.HasOne("FuelStation.ReservationService.Persistence.Entities.PumpEntity", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelStation.ReservationService.Persistence.Entities.TankEntity", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pump");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.NozzleEntity", b =>
                {
                    b.HasOne("FuelStation.ReservationService.Persistence.Entities.PumpEntity", "Pump")
                        .WithMany("Nozzles")
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelStation.ReservationService.Persistence.Entities.TankEntity", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pump");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.DeliverySessionEntity", b =>
                {
                    b.Navigation("Compartments");
                });

            modelBuilder.Entity("FuelStation.ReservationService.Persistence.Entities.PumpEntity", b =>
                {
                    b.Navigation("Nozzles");
                });
#pragma warning restore 612, 618
        }
    }
}
